const events = [
  {
    id: 1,
    title: "Test",
    description: "Sample event for dashboard",
    date: "Mar 27, 2026",
    time: "10:00 AM",
    venue: "gag",
    category: "Conference",
    status: "Upcoming",
    featured: true,
    draft: false,
    image: "",
    capacity: 2,
    bookedCount: 1,
    waitingCount: 0,
  },
  {
    id: 2,
    title: "Hackathon 2026",
    description: "Coding and innovation event",
    date: "Apr 10, 2026",
    time: "09:00 AM",
    venue: "Main Hall",
    category: "Competition",
    status: "Upcoming",
    featured: false,
    draft: false,
    image: "",
    capacity: 1,
    bookedCount: 1,
    waitingCount: 2,
  },
  {
    id: 3,
    title: "Workshop Draft",
    description: "Draft sample event",
    date: "Apr 15, 2026",
    time: "02:00 PM",
    venue: "Lab 2",
    category: "Workshop",
    status: "Draft",
    featured: false,
    draft: true,
    image: "",
    capacity: 3,
    bookedCount: 0,
    waitingCount: 0,
  },
];

export default events;